###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://www.ory.sh/docs/hydra/5min-tutorial                            #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

version: '3.4'

x-hydra-variables: &hydra-variables
  # Service registry
  HYDRA_PUBLIC_ROOT: 'http://127.0.0.1:4444'
  HYDRA_ADMIN_ROOT: 'http://hydra:4445'
  OAUTH_CLIENT_ID: 'poc-client'
  OAUTH_CLIENT_SECRET: 'poc-secret'
  OAUTH_CALLBACK_URI: 'http://127.0.0.1:7500/oauth2/finish'

services:

  identity:
    build:
      context: identityserver/
    ports:
      - '7501:8000'
    volumes:
      - ./identityserver:/opt/app
    environment:
      <<: *hydra-variables
      DEFAULT_DATABASE: 'postgres://hydra:secret@postgresd:5432/identity'

  resource:
    build:
      context: resourceserver/
    ports:
      - '7500:8000'
    volumes:
      - ./resourceserver:/opt/app
    environment:
      <<: *hydra-variables
      DEFAULT_DATABASE: 'postgres://hydra:secret@postgresd:5432/resource'

  hydra:
    image: oryd/hydra:latest
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:7501/consent
      - URLS_LOGIN=http://127.0.0.1:7501/login
      - URLS_LOGOUT=http://127.0.0.1:3000/logout
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=public
      - OAUTH2_ACCESS_TOKEN_STRATEGY=jwt
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=1
      - LOG_LEVEL=debug
    restart: unless-stopped

  hydra-migrate:
    image: oryd/hydra:latest
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra

  wait_for_postgres:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgresd
    command: postgresd:5432
